requires = [
    "setuptools>=42",
    "wheel",
    "numpy",
    "requests",
    "tqdm>=4.47.0",
    "regex",
    "transformers>=4.6.0",
    "datasets" "seqeval",
    "torch",
    "pandas",
    "tokenizers",
]

[
    "computational phantoms",
    "monte carlo calculations",
    "in vivo measurements",
    "radionuclides",
    "tissues",
    "worker",
    "precise geometric representation",
    "mcnp input data file",
    "scanning data",
    "computed tomography",
    "brightness",
    "graphical user interface",
    "computation phantoms",
    "calibration",
    "in vivo measurement systems",
    "signal",
    "detector",
    "individual voxels",
    "memory demand",
    "calculational speed",
    "plastic",
    "magnetic resonance imaging scanning information",
    "anatomy",
    "low energy gamma ray emitting sources",
    "actinides",
    "software",
    "automatic creation",
]
